<section id="breadcrumbs">
    <div class="container">
            <div class="span10 ">
                <ul class="breadcrumb" style="min-height: 20px">
                    <!--phpMyEngine::breadcrumbs/-->
                </ul>
            </div>
            <div class="span2 pull-right text-center">
                <a href="#" class="updownbtn" id="move_up">
                    <i class="icon-chevron-up"></i> <span>наверх</span>
                </a>
                <a href="#" class="updownbtn" id="move_down">
                    <i class="icon-chevron-down"></i> обратно
                </a>
            </div>
    </div>
</section>